services:
  - type: web
    name: proplan-activity-provider
    env: python
    region: frankfurt         
    plan: free                
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
